def cta_texts(request):
    """
    Context processor that provides CTA texts across all templates
    """
    return {
        'HERO_CTA_SCHEDULE': 'Schedule Free Consultation',
        'HERO_CTA_ESTIMATE': 'Get Project Estimate',
        'GET_IN_TOUCH_CTA': 'Get in Touch',
        'CTA_FREE_IT_REVIEW': 'Get your free IT review',
        'CTA_GRAPHIC_DESIGN_SOLUTIONS': 'Start Your Design Story',
        'CTA_VISUAL_SOLUTIONS': 'Start Your Visual Solutions',
        'CTA_INDUSTRY_SOLUTIONS': 'Request Custom Solutions',
        'CTA_DEVELOPMENT_PROCESSES': 'Schedule Free Consultation',
        'CTA_RISK_FREE_TRIAL': 'Start Your Risk-Free Trial',
        'CTA_START_DEVELOPMENT_PLANNING': 'Start Development Planning',
        'CTA_START_YOUR_WEB_PROJECT': 'Start Your Web Project',
        'CTA_START_YOUR_DB_PROJECT': 'Start Your Database Project',
        'CTA_GET_EXPERT_GUIDANCE': 'Get Expert Guidance',
        'CTA_SCHEDULE_YOUR_ASSESSMENT': 'Schedule Your Assessment',
        'CTA_BEGIN_YOUR_DESIGN_JOURNEY': 'Begin Your Design Journey',
        'CTA_SCHEDULE_MOBILE_DISCUSSION': 'Schedule Mobile Project Discussion',
        'CTA_SCHEDULE_TECHNICAL_CONSULTATION': 'Schedule Technical Consultation',
        'CTA_START_YOUR_DESKTOP_PROJECT': 'Start Your Desktop Project',
        'CTA_CUSTOM_SOLUTION': 'Request Custom Solution',
        'CTA_FREE_CONSULTATION': 'Schedule Free Consultation',
        'CTA_TECH_CONSULTATION': 'Schedule Technical Consultation',
        'CTA_DATABASE_PROJECT': 'Start Your Database Project',
        'CTA_CONTACT_NOW': 'Contact Us Now',
        'CTA_GET_STARTED': 'Get Started Today',
        'CTA_QUOTE': 'Get Precise Quote',
        'CTA_LEARN_MORE': 'Learn More',
        'CTA_START_YOUR_PROJECT': 'Start Your Project',
        'CTA_LETS_DISCUSS_YOUR_IDEAS': "Let's Discuss Your Ideas",
        'CTA_START_JAVA_PROJECT': 'Start Java Project',
        'CTA_START_PYTHON_PROJECT': 'Start Python Project',
        'CTA_START_DOTNET_PROJECT': 'Start C# Project',
        'CTA_START_CPP_PROJECT': 'Start C++ Project',
        'CTA_START_JAVASCRIPT_PROJECT': 'Start JavaScript Project',
        'CTA_START_SWIFT_PROJECT': 'Start Swift Project',
        'CTA_START_POSTGRESQL_PROJECT': 'Optimize Your Database',
        'CTA_GET_REMOTE_SUPPORT': 'Get Remote Support',
        'CTA_START_CREATIVE_PROJECT': 'Start Creative Project',
        'CTA_TRANSFORM_HEALTHCARE': 'Transform Healthcare',
        'CTA_MODERNIZE_FINANCE': 'Modernize Finance',
        'CTA_ENHANCE_EDUCATION': 'Enhance Education',
        'CTA_ELEVATE_RETAIL': 'Elevate Retail',
        'CTA_OPTIMIZE_MANUFACTURING': 'Optimize Manufacturing',
        'CTA_IMPROVE_INSURANCE': 'Improve Insurance',
        'CTA_OPTIMIZE_LOGISTICS': 'Optimize Logistics',
        'CTA_LAUNCH_MEDIA_PLATFORM': 'Launch Media Platform',
        'CTA_GET_ENTERPRISE_QUOTE': 'Get Enterprise Quote',
        'CTA_REQUEST_CUSTOM_QUOTE': 'Request Custom Quote',
        'CTA_BUILD_YOUR_WEB_PRESENCE': 'Build Your Web Presence',
        'CTA_LAUNCH_ONLINE_STORE': 'Launch Online Store',
        'CTA_REQUEST_CONSULTATION': 'Request Free Consultation',
        'CTA_LAUNCH_YOUR_MVP': 'Launch Your MVP',
        'CTA_SCALE_YOUR_APP': 'Scale Your App',
        'CTA_BUILD_ENTERPRISE_SOLUTION': 'Build Enterprise Solution',
        'CTA_START_BASIC_PLAN': 'Start Basic Plan',
        'CTA_CHOOSE_PROFESSIONAL_PLAN': 'Choose Professional Plan',
        'CTA_OPTIMIZE_YOUR_DATA': 'Optimize Your Database',
        'CTA_BOOK_HALF_DAY': 'Book Half Day',
        'CTA_BOOK_FULL_DAY': 'Book Full Day',
        'CTA_DEVELOP_DESKTOP_SOLUTION': 'Develop Desktop Solution',
        'CTA_BUILD_YOUR_MOBILE_APP': 'Build Your Mobile App',
        'CTA_LEARN_MORE': 'Learn More',
    }