# Generated by Django 5.2 on 2026-01-07 16:44

import admin.apps.forms.models.form_attachment
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('services', models.JSONField(default=list)),
                ('other_service', models.CharField(blank=True, max_length=100, null=True)),
                ('project_description', models.TextField()),
                ('budget_range', models.CharField(blank=True, max_length=50, null=True)),
                ('timeline', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('converted', 'Converted'), ('archived', 'Archived')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('response_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Requirement',
                'verbose_name_plural': 'Client Requirements',
                'db_table': 'client_requirements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=admin.apps.forms.models.form_attachment.attachment_upload_path)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('uploaded_by_user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forms.clientrequirement')),
            ],
            options={
                'verbose_name': 'Form Attachment',
                'verbose_name_plural': 'Form Attachments',
                'db_table': 'form_attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
