# Generated by Django 5.2 on 2026-01-12 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_clientrequirement_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrequirement',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='formattachment',
            name='client_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='clientrequirement'),
        ),
        migrations.DeleteModel(
            name='ClientRequirement',
        ),
    ]
